"""add_event_id_to_audit_logs

Revision ID: b54588cd42f1
Revises: 0001_add_devices_and_vdoms
Create Date: 2026-09-02 09:28:17.128026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b54588cd42f1'
down_revision: Union[str, Sequence[str], None] = '0001_add_devices_and_vdoms'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'event_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               nullable=True,
               comment='Identificador único del evento en el bus (Redis/MQ) para trazabilidad e idempotencia')
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=45),
               nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               nullable=True)
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.drop_column('audit_logs', 'occurred_at')
    op.drop_column('audit_logs', 'correlation_id')
    op.alter_column('device_vdoms', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.create_unique_constraint(None, 'devices', ['serial_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=True)
    op.alter_column('device_vdoms', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('audit_logs', sa.Column('correlation_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('audit_logs', 'event_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               nullable=False,
               comment=None,
               existing_comment='Identificador único del evento en el bus (Redis/MQ) para trazabilidad e idempotencia')
    # ### end Alembic commands ###
