"""add client_id to devices

Revision ID: 7b36888b8ee0
Revises: b54588cd42f1
Create Date: 2026-09-03 16:21:20.267464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b36888b8ee0'
down_revision: Union[str, Sequence[str], None] = 'b54588cd42f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_devices_client_id'), 'devices', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_client_id'), table_name='devices')
    op.drop_column('devices', 'client_id')
    # ### end Alembic commands ###
