"""add_is_active_to_hardening_profiles

Revision ID: 9a94ce3d336b
Revises: 7b36888b8ee0
Create Date: 2026-09-15 14:13:11.857729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a94ce3d336b'
down_revision: Union[str, Sequence[str], None] = '7b36888b8ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_vdoms_client_id'), table_name='device_vdoms')
    op.drop_index(op.f('ix_device_vdoms_device_id'), table_name='device_vdoms')
    op.drop_table('device_vdoms')
    op.add_column('hardening_profiles', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hardening_profiles', 'is_active')
    op.create_table('device_vdoms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_root', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('device_vdoms_client_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('device_vdoms_device_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('device_vdoms_pkey')),
    sa.UniqueConstraint('device_id', 'name', name=op.f('uq_device_vdom_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_device_vdoms_device_id'), 'device_vdoms', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_vdoms_client_id'), 'device_vdoms', ['client_id'], unique=False)
    # ### end Alembic commands ###
