"""add_standard_version_to_rule_catalog

Revision ID: 7fc05d94c2f4
Revises: 9a94ce3d336b
Create Date: 2026-09-16 08:51:25.814422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fc05d94c2f4'
down_revision: Union[str, Sequence[str], None] = '9a94ce3d336b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_vdoms_client_id'), table_name='device_vdoms')
    op.drop_index(op.f('ix_device_vdoms_device_id'), table_name='device_vdoms')
    op.drop_table('device_vdoms')
    op.add_column(
        'hardening_rule_catalog', 
        sa.Column('standard_version', sa.String(length=20), server_default='v1.0.0', nullable=False)
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hardening_rule_catalog', 'standard_version')
    op.create_table('device_vdoms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_root', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('device_vdoms_client_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('device_vdoms_device_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('device_vdoms_pkey')),
    sa.UniqueConstraint('device_id', 'name', name=op.f('uq_device_vdom_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_device_vdoms_device_id'), 'device_vdoms', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_vdoms_client_id'), 'device_vdoms', ['client_id'], unique=False)
    # ### end Alembic commands ###
